name: Build and Push Docker container

on: 
  push:
    branches:
      - main

  workflow_dispatch:
    

env:  
  containertag: ghcr.io/rajbos/dind-rootless-runner
  containerhost: https://ghcr.io

jobs:
  build-and-push-main:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build -t $containertag .

    - name: Setup GitHub Container Registry
      run: echo "${{ secrets.GH_PAT }}" | docker login $containerhost -u ${{ github.actor }} --password-stdin

    - name: Push to GitHub Container Registry
      run:  docker push $containertag

    - name: Cleanup GitHub Container Registry login data
      run: docker logout $containerhost

    - name: Run Snyk to check Docker image for vulnerabilities
      if: ${{ true }}  # enable for now
      uses: rajbos-actions/snyk-actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:      
        image: ${{ env.containertag }}
        args: --file=Dockerfile
      continue-on-error: true

    - name: Upload Snyk scan result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif


  build-and-push-branch:

    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build -t $containertag:${GITHUB_REF##*/} .

    - name: Setup GitHub Container Registry
      run: echo "${{ secrets.GH_PAT }}" | docker login $containerhost -u ${{ github.actor }} --password-stdin

    - name: Push to GitHub Container Registry
      run:  docker push $containertag:${GITHUB_REF##*/}

    - name: Cleanup GitHub Container Registry login data
      run: docker logout $containerhost

    - name: Run Snyk to check Docker image for vulnerabilities
      uses: rajbos-actions/snyk-actions/docker@master      
      if: ${{ true }}  # enable for now
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        CONTAINER_TAG: $containertag:${GITHUB_REF##*/}
      with:
        image: ${{ env.containertag }}
        args: --file=Dockerfile

    - name: Upload Snyk scan result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
        image: ghcr.io/rajbos/local-dependency-updates:test